'use strict';
// test/codebuddy-adapter.test.js - grill-t30 D-002: CodeBuddy plugin-bundle
// structure + behavior pins (the first Claude-Code-compatible path host,
// ADR-0087). Bundle = adapters/codebuddy/, generated by build-adapters.js
// (golden layer) - these tests pin the STRUCTURE and the live hook
// semantics the contract matrix cannot see (InstructionsLoaded telemetry,
// PreToolUse deny envelope).

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const BUNDLE = path.join(ROOT, 'adapters', 'codebuddy');
const EVENTS = ['SessionStart', 'SubagentStart', 'UserPromptSubmit', 'Stop', 'SessionEnd', 'InstructionsLoaded', 'PreToolUse'];
const HOOK_SCRIPTS = ['jiahao-activate', 'jiahao-subagent', 'jiahao-mode-tracker', 'jiahao-verdict-gate', 'jiahao-sweep', 'jiahao-instructions-assert', 'jiahao-pretool-guard'];
const SUPPORT_LIBS = ['jiahao-runtime', 'jiahao-profile']; // require() deps, not event handlers

function mkConfigDir(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'jiahao-cb-'));
  fs.writeFileSync(path.join(dir, '.jiahao-active'), 'full');
  for (const name of Object.keys(files || {})) {
    fs.writeFileSync(path.join(dir, name), files[name], 'utf8');
  }
  return dir;
}

function runBundleHook(script, opts) {
  const o = opts || {};
  const env = Object.assign({}, process.env);
  delete env.PLUGIN_DATA;
  delete env.COPILOT_PLUGIN_DATA;
  delete env.QODER_SESSION_ID;
  delete env.CLAUDE_PLUGIN_ROOT;
  delete env.CODEBUDDY_PLUGIN_ROOT;
  env.CLAUDE_CONFIG_DIR = o.configDir;
  if (o.pluginRoot !== undefined) env.CLAUDE_PLUGIN_ROOT = o.pluginRoot;
  return spawnSync(process.execPath, [path.join(BUNDLE, 'hooks', script)], {
    input: o.stdin === undefined ? '{}' : o.stdin,
    env: env, encoding: 'utf8', timeout: 15000,
  });
}

describe('bundle structure (spec 2.2: manifest-dir-only, components at root)', () => {
  test('plugin.json exists ONLY inside .claude-plugin/ - no stray root manifest', () => {
    expect(fs.existsSync(path.join(BUNDLE, '.claude-plugin', 'plugin.json'))).toBe(true);
    expect(fs.existsSync(path.join(BUNDLE, 'plugin.json'))).toBe(false);
  });

  test('component files sit at bundle root: hooks/, rules/, .mcp.json, jiahao-mcp/, README', () => {
    for (const p of ['hooks/hooks.json', 'rules/jiahao-verifier.md', 'rules/jiahao-generator.md',
      '.mcp.json', 'jiahao-mcp/index.js', 'jiahao-mcp/package.json', 'src/SKILL.md', 'README.md']) {
      expect(fs.existsSync(path.join(BUNDLE, p))).toBe(true);
    }
  });

  test('manifest pins the real component paths and the conservative default', () => {
    const m = JSON.parse(fs.readFileSync(path.join(BUNDLE, '.claude-plugin', 'plugin.json'), 'utf8'));
    expect(m.name).toBe('jiahao');
    expect(m.hooks).toBe('hooks/hooks.json');
    expect(m.mcpServers).toBe('.mcp.json');
    expect(m.defaultEnabled).toBe(false);
    expect(fs.existsSync(path.join(BUNDLE, m.hooks))).toBe(true);
    expect(fs.existsSync(path.join(BUNDLE, m.mcpServers))).toBe(true);
  });

  test('hooks.json registers the full seven-event map incl. InstructionsLoaded + PreToolUse', () => {
    const cfg = JSON.parse(fs.readFileSync(path.join(BUNDLE, 'hooks', 'hooks.json'), 'utf8'));
    for (const ev of EVENTS) {
      expect(Array.isArray(cfg.hooks[ev])).toBe(true);
      for (const entry of cfg.hooks[ev]) {
        for (const h of entry.hooks) {
          expect(h.timeout).toBeLessThanOrEqual(60);
          expect(h.command).toContain('${CLAUDE_PLUGIN_ROOT}/hooks/');
          const script = h.command.match(/hooks\/([a-z0-9-]+\.js)/);
          expect(script).not.toBeNull();
          expect(fs.existsSync(path.join(BUNDLE, 'hooks', script[1]))).toBe(true);
        }
      }
    }
    // the vendored hooks/ dir is exactly: the 7 wired handlers + 2 support
    // libs (runtime/profile) - nothing orphaned, nothing missing
    const vendored = fs.readdirSync(path.join(BUNDLE, 'hooks')).filter((f) => /^jiahao-.*\.js$/.test(f));
    expect(vendored.sort()).toEqual(HOOK_SCRIPTS.concat(SUPPORT_LIBS).map((s) => s + '.js').sort());
  });

  test('vendored hook scripts are byte-verbatim copies of the repo sources', () => {
    for (const s of HOOK_SCRIPTS) {
      const a = fs.readFileSync(path.join(BUNDLE, 'hooks', s + '.js'), 'utf8');
      const b = fs.readFileSync(path.join(ROOT, 'hooks', s + '.js'), 'utf8');
      expect(a).toBe(b);
    }
    const mcpA = fs.readFileSync(path.join(BUNDLE, 'jiahao-mcp', 'index.js'), 'utf8');
    const mcpB = fs.readFileSync(path.join(ROOT, 'jiahao-mcp', 'index.js'), 'utf8');
    expect(mcpA).toBe(mcpB);
    const skA = fs.readFileSync(path.join(BUNDLE, 'src', 'SKILL.md'), 'utf8');
    const skB = fs.readFileSync(path.join(ROOT, 'src', 'SKILL.md'), 'utf8');
    expect(skA).toBe(skB);
  });

  test('rules carry alwaysApply frontmatter and both distinct profiles', () => {
    const v = fs.readFileSync(path.join(BUNDLE, 'rules', 'jiahao-verifier.md'), 'utf8');
    const g = fs.readFileSync(path.join(BUNDLE, 'rules', 'jiahao-generator.md'), 'utf8');
    for (const t of [v, g]) {
      expect(t).toMatch(/alwaysApply:\s*true/);
      expect(/jiahao/i.test(t)).toBe(true);
    }
    expect(v).toContain('Verifier Profile');
    expect(g).toContain('Generator Profile');
    expect(v).not.toBe(g);
  });

  test('.mcp.json references the vendored jiahao-mcp entry', () => {
    const mcp = JSON.parse(fs.readFileSync(path.join(BUNDLE, '.mcp.json'), 'utf8'));
    expect(mcp.mcpServers['jiahao-mcp'].command).toBe('node');
    const rel = mcp.mcpServers['jiahao-mcp'].args[0].replace('${CLAUDE_PLUGIN_ROOT}', BUNDLE);
    expect(fs.existsSync(rel)).toBe(true);
  });
});

describe('hook behavior (bundle copies, live spawn)', () => {
  test('InstructionsLoaded asserts rules presence + sha256 into the telemetry log', () => {
    const dir = mkConfigDir({ '.jiahao-profile': 'verifier' });
    const res = runBundleHook('jiahao-instructions-assert.js', { configDir: dir, pluginRoot: BUNDLE });
    expect(res.status).toBe(0);
    const log = fs.readFileSync(path.join(dir, '.jiahao-instructions.jsonl'), 'utf8');
    const rec = JSON.parse(log.trim().split('\n').pop());
    expect(rec.event).toBe('InstructionsLoaded');
    expect(rec.results.length).toBe(2);
    for (const r of rec.results) {
      expect(r.present).toBe(true);
      expect(r.sha256).toMatch(/^[0-9a-f]{64}$/);
      expect(r.alwaysApply).toBe(true);
    }
  });

  test('InstructionsLoaded records absent rules honestly when the root lacks them', () => {
    const dir = mkConfigDir({ '.jiahao-profile': 'verifier' });
    const emptyRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'jiahao-cb-root-'));
    const res = runBundleHook('jiahao-instructions-assert.js', { configDir: dir, pluginRoot: emptyRoot });
    expect(res.status).toBe(0);
    const rec = JSON.parse(fs.readFileSync(path.join(dir, '.jiahao-instructions.jsonl'), 'utf8').trim().split('\n').pop());
    expect(rec.results.every((r) => r.present === false)).toBe(true);
  });

  test('PreToolUse denies an enforcement-surface edit under verifier profile (envelope, exit 0)', () => {
    const dir = mkConfigDir({ '.jiahao-profile': 'verifier' });
    const res = runBundleHook('jiahao-pretool-guard.js', {
      configDir: dir, pluginRoot: BUNDLE,
      stdin: JSON.stringify({ tool_name: 'Edit', tool_input: { file_path: 'adapters/codebuddy/rules/jiahao-verifier.md' } }),
    });
    expect(res.status).toBe(0);
    const out = JSON.parse(res.stdout.trim());
    expect(out.hookSpecificOutput.permissionDecision).toBe('deny');
    expect(out.hookSpecificOutput.hookEventName).toBe('PreToolUse');
    const rec = JSON.parse(fs.readFileSync(path.join(dir, '.jiahao-pretool.jsonl'), 'utf8').trim().split('\n').pop());
    expect(rec.decision).toBe('deny');
  });

  test('PreToolUse denies command-payload bypass shapes (audit B-4 regression)', () => {
    const dir = mkConfigDir({ '.jiahao-profile': 'verifier' });
    const shapes = [
      'rm rules/jiahao-verifier.md',
      'rm .mcp.json',
      'del hooks\\hooks.json',
      'rm C:/x/plugin/rules/jiahao-verifier.md extra',
      'cat .jiahao-pretool.jsonl',
      'rm -rf hooks/jiahao-pretool-guard.js',
      'move .claude-plugin/plugin.json out.json',
    ];
    for (const command of shapes) {
      const res = runBundleHook('jiahao-pretool-guard.js', {
        configDir: dir, pluginRoot: BUNDLE,
        stdin: JSON.stringify({ tool_name: 'Bash', tool_input: { command: command } }),
      });
      expect(res.status).toBe(0);
      const out = JSON.parse(res.stdout.trim());
      expect(out.hookSpecificOutput.permissionDecision).toBe('deny');
    }
    // non-protected payloads still pass silently
    const benign = runBundleHook('jiahao-pretool-guard.js', {
      configDir: dir, pluginRoot: BUNDLE,
      stdin: JSON.stringify({ tool_name: 'Bash', tool_input: { command: 'rm rules/other.md && cat README.md' } }),
    });
    expect(benign.stdout.trim()).toBe('');
  });

  test('PreToolUse is silent on ordinary tool calls and under generator profile', () => {
    const dir = mkConfigDir({ '.jiahao-profile': 'verifier' });
    const benign = runBundleHook('jiahao-pretool-guard.js', {
      configDir: dir, pluginRoot: BUNDLE,
      stdin: JSON.stringify({ tool_name: 'Write', tool_input: { file_path: 'src/foo.js' } }),
    });
    expect(benign.status).toBe(0);
    expect(benign.stdout.trim()).toBe('');

    const dirG = mkConfigDir({ '.jiahao-profile': 'generator' });
    const gen = runBundleHook('jiahao-pretool-guard.js', {
      configDir: dirG, pluginRoot: BUNDLE,
      stdin: JSON.stringify({ tool_name: 'Edit', tool_input: { file_path: '.codebuddy/rules/jiahao-verifier.md' } }),
    });
    expect(gen.status).toBe(0);
    expect(gen.stdout.trim()).toBe(''); // observe-recorded, never denied
    const rec = JSON.parse(fs.readFileSync(path.join(dirG, '.jiahao-pretool.jsonl'), 'utf8').trim().split('\n').pop());
    expect(rec.decision).toBe('observe');
  });

  test('both new hooks are fail-soft on empty and garbage stdin', () => {
    for (const s of ['jiahao-instructions-assert.js', 'jiahao-pretool-guard.js']) {
      const a = runBundleHook(s, { configDir: mkConfigDir(), stdin: '' });
      const b = runBundleHook(s, { configDir: mkConfigDir(), stdin: 'not json{{{' });
      expect(a.status).toBe(0);
      expect(b.status).toBe(0);
    }
  });
});
